resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.5

jobs:
- job: Linux

  container: nv-bionic-wasm

  timeoutInMinutes: 120

  workspace:
    clean: all

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget
    EMSCRIPTEN_VERSION: 1.39.7

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y default-jdk
    
    displayName: Install Java

  - bash: |
      cd ~
      echo Installing emscripten $(EMSCRIPTEN_VERSION)
      git clone https://github.com/emscripten-core/emsdk
      cd ~/emsdk
      ./emsdk install $(EMSCRIPTEN_VERSION)
      ./emsdk activate $(EMSCRIPTEN_VERSION)

    displayName: 'Setup Emscripten'

  - bash: |
      python tools/git-sync-deps
      ./bin/fetch-gn

    displayName: Sources Setup

  - bash: |
     source ~/emsdk/emsdk_env.sh
     experimental/canvaskit/compile.sh

    displayName: Package wasm

  - bash: |
      cp -R out/canvaskit_wasm/* $(build.artifactstagingdirectory)

    displayName: Copy files

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: skia-wasm
      ArtifactType: Container
